peluqueria/urls.py
from django.contrib import admin
from django.urls import path

from . import views

from appointment import views as views_appointment

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('create_appointment/',views_appointment.CreateAppointment.as_view(),name='create'),
    path('list_appointment/',views_appointment.ListAppointment.as_view(),name='list'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
]

account/models.py
from django.db import models

# Create your models here.

appointment/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone

class Appointment(models.Model):
	user = models.EmailField()
	create_date = models.DateTimeField(default=timezone.now)
	appointment_date = models.DateTimeField()

	def __str__(self):
		return self.user

	def get_absolute_url(self):
		return reverse('home')

appointment/forms.py
from django import forms

from appointment.models import Appointment

from django.utils import timezone

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('user','appointment_date')

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)

        self.fields['appointment_date'] = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

    def clean_appointment_date(self):
        data = self.cleaned_data['appointment_date']
        list_of_appointments = Appointment.objects.filter(appointment_date__exact=data)

        if len(list_of_appointments) > 0:
            raise forms.ValidationError("Ya hay un turno reservado")

        start_time = timezone.now().replace(microsecond=0, second=0, minute=0)
        if data < start_time:
            raise forms.ValidationError("No puede solicitar un turno para esa fecha")


        return data

account/views.py
from django.shortcuts import render

# Create your views here.

appointment/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic

from appointment import forms
from appointment.models import Appointment

from datetime import date, timedelta

from django.utils import timezone

class CreateAppointment(generic.CreateView):
	form_class = forms.AppointmentForm
	model = Appointment

	def get_context_data(self, **kwargs):
	 	context = super().get_context_data(**kwargs)
	 	all_appointments = Appointment.objects.filter(appointment_date__gt=date.today()).order_by('appointment_date')

	 	start_time = timezone.now().replace(microsecond=0, second=0, minute=0, hour=9)
	 	counter = 0

	 	free_appointments = []

	 	while counter < 5:
	 		free_slot = True
	 		for appointment in all_appointments:
	 			if appointment.appointment_date == start_time:
	 				free_slot = False
	 				break

	 			if appointment.appointment_date > start_time:
	 				break
			
	 		if free_slot:
 				free_appointments.append(start_time)
 				counter += 1

	 		start_time = start_time + timedelta(hours=0.5)

	 	context['free_appointments'] = free_appointments

	 	return context

class ListAppointment(generic.ListView):
	model = Appointment

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.order_by('appointment_date')

peluqueria/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
	template_name = 'test.html'

class ThanksPage(TemplateView):
	template_name = 'thanks.html'

class HomePage(TemplateView):
	template_name = 'index.html'

appointment/templates/appointment/appointment_base.html
{% extends "base.html" %}

{% block content %}
	
	<div class="container-fluid">
	
		{% block group_content %} {% endblock %}
		<div class="row">
			{% block pregroup %} {% endblock %}
			{% block postgroup %} {% endblock %}
		</div>
		
	</div>
	{% block footer %} {% endblock %}
	

{% endblock %}

appointment/templates/appointment/appointment_form.html
{% extends "appointment/appointment_base.html" %}
{% load bootstrap4 %}
{% block group_content %}

	<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
	
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 order-md-1">
				<form method="POST">
					{% csrf_token %}
					{% bootstrap_form form %}			

					<input type="submit" class='btn btn-primary btn-large' value="Crear">
					
				</form>
			</div>

			<div class="col order-1">
				<div class="container col-6">
					<h4>Próximos turnos disponibles</h4>
					<br>
					<div class="list-group">
						{% for appointment in free_appointments %}
							<div class="list-group-item list-group-item-action d-flex w-100 justify-content-between">
						    	<h5 class="mb-1">{{ appointment|date:'d/m/Y H:i' }}</h5>
						    </div> 
						    <br>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
	
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	<!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

	<script>
		$(function () {
		    $("#id_appointment_date").datetimepicker({
		      format: 'd/m/Y H:i',
		      minTime:'09:00',
		      step: 30,
		      maxTime:'18:00',
		    });
  		});

		$('.list-group-item').on('click', function() {
			console.log("Click!")
			var $this = $(this);
			var $children = $this.children('h5'); //get the appointment date

			$('#id_appointment_date').val($children.text());

			console.log($children.text())
			console.log("$('#appointment_date').val($children.text());")
		});
	
	</script>

{% endblock %}

appointment/templates/appointment/appointment_list.html
{% extends "appointment/appointment_base.html" %}
{% load bootstrap4 %}
{% block group_content %}
	<div class="col order-1">
		<div class="list-budget">
			{% for appointment in object_list %}
				<div class="list-group-item list-group-item-action d-flex w-100 justify-content-between">
			    	<h5 class="mb-1">{{ appointment.user }}</h5>
			    	<h5 class="mb-1">{{ appointment.appointment_date|date:'d/m/Y H:i' }}</h5>
			    </div> 
			    <br>
			{% endfor %}
		</div>	
	</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Titulo de la Web</title>

	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
	
	<!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet"> -->
	<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>

	<!-- Bootstrap  -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<!-- Own css file  -->
	<link rel="stylesheet" href="{% static 'peluqueria/css/master.css' %}">

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark techfont mynav" id='navbar'>
		<a class='navbar-brand mynav' href="{% url 'home' %}">Home</a>
		<ul class='nav navbar-nav navbar-right ml-auto'>
			<li><a class="nav-link" href="{% url 'list' %}">Turnos Reservados</a></li>
			<li><a class="nav-link" href="{% url 'create' %}">Reservar Turno</a></li>
		</ul>
	</nav>

	<div class="container-fluid">
		{% block content %}

		{% endblock %}
	</div>

</body>
<script src="{% static 'peluqueria/js/master.js'%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

	<h1>Bienvenido a Titulo de la Web!</h1>

{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block content %}

	<h1>This is a test page!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block content %}

	<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}